
// Define the available chart types
export enum ChartType {
  BAR = 'bar',
  LINE = 'line',
  PIE = 'pie',
  AREA = 'area',
  KPICARD = 'kpi'
}

// Represents a single data point in a chart
export interface DataPoint {
  [key: string]: any;
}

export interface AlertConfig {
  id: string;
  type: 'above' | 'below';
  threshold: number;
  message: string;
  triggered?: boolean;
}

// The configuration generated by the AI for a specific dashboard widget
export interface DashboardWidgetConfig {
  id: string;
  title: string;
  description: string;
  chartType: ChartType;
  odataQuery: string; // Used for OData
  sqlQuery?: string;  // Used for BigQuery/SQL
  xAxisKey: string;
  dataKey: string;
  entity: string; // The base entity name for drill-down context
  alerts?: AlertConfig[];
}

export interface SchemaField {
  name: string;
  type: string;
  description?: string;
}

export interface SchemaEntity {
  name: string;
  fields: SchemaField[];
}

export interface DatabaseSchema {
  entities: SchemaEntity[];
}

// --- New Types for Visual AI Analysis ---

export interface InsightMetric {
  label: string;
  value: string | number;
  change?: string; // e.g., "+5%" or "Stable"
  trend: 'up' | 'down' | 'neutral';
  color?: string;
}

export interface InsightChartData {
  title: string;
  type: 'bar' | 'line' | 'pie';
  data: { name: string; value: number }[];
  description?: string;
}

export interface InsightFinding {
  title: string;
  description: string;
  severity: 'high' | 'medium' | 'low';
}

export interface AnalysisResult {
  id: string;          // Unique ID for saving
  createdAt: string;   // Timestamp
  sourceEntity: string; // Context for drill-down
  summary: string;
  metrics: InsightMetric[];
  charts: InsightChartData[];
  findings: InsightFinding[];
}
